export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const CLEAR_FAVORITES = "CLEAR_FAVORITES";

export const UPDATE_CURRENT_LISTING = "UPDATE_CURRENT_LISTING"